### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [3]:
#code
import numpy as np
a=np.random.randint(1,100,15)
print(a)

[88 77 12 73 89 77 15 58 27 43 38 80 81 37 26]


In [2]:
np.sort(a)

array([ 4, 25, 28, 39, 39, 42, 47, 53, 54, 58, 60, 61, 70, 85, 95])

In [4]:
b=np.random.randint(1,100,24).reshape(6,4)
print(b)

[[ 2 97  2 84]
 [ 3 80 38  1]
 [54 94 56 74]
 [57 34 96 75]
 [45 47 33  8]
 [38  7 93 71]]


In [5]:
#isme row wisse sorting hua hai
np.sort(b)

array([[ 2,  2, 84, 97],
       [ 1,  3, 38, 80],
       [54, 56, 74, 94],
       [34, 57, 75, 96],
       [ 8, 33, 45, 47],
       [ 7, 38, 71, 93]])

In [8]:
#isme column wise sort hua hai
np.sort(b,axis=0)

array([[ 2,  7,  2,  1],
       [ 3, 34, 33,  8],
       [38, 47, 38, 71],
       [45, 80, 56, 74],
       [54, 94, 93, 75],
       [57, 97, 96, 84]])

In [10]:
#for descending wose sorting
np.sort(a)[::-1]

array([89, 88, 81, 80, 77, 77, 73, 58, 43, 38, 37, 27, 26, 15, 12])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [11]:
#code a=np.append(array ka naam ,kaunsa element dalna hai)
a=np.append(a,200)

In [12]:
a

array([ 88,  77,  12,  73,  89,  77,  15,  58,  27,  43,  38,  80,  81,
        37,  26, 200])

In [14]:
#2D array
b

array([[ 2, 97,  2, 84],
       [ 3, 80, 38,  1],
       [54, 94, 56, 74],
       [57, 34, 96, 75],
       [45, 47, 33,  8],
       [38,  7, 93, 71]])

In [16]:
#ek column add karna hai wo bhi last mei
np.append(b,np.ones((b.shape[0],1)),axis=1)


array([[ 2., 97.,  2., 84.,  1.],
       [ 3., 80., 38.,  1.,  1.],
       [54., 94., 56., 74.,  1.],
       [57., 34., 96., 75.,  1.],
       [45., 47., 33.,  8.,  1.],
       [38.,  7., 93., 71.,  1.]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [17]:
#code
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)

print(c)
print(d)


[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [19]:
np.concatenate((c,d),axis=0) #for row

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [20]:
np.concatenate((c,d),axis=1) # for column


array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [21]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [23]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [24]:
#code
a

array([ 88,  77,  12,  73,  89,  77,  15,  58,  27,  43,  38,  80,  81,
        37,  26, 200])

In [29]:
np.expand_dims(a,axis=0)

array([[ 88,  77,  12,  73,  89,  77,  15,  58,  27,  43,  38,  80,  81,
         37,  26, 200]])

In [30]:
np.expand_dims(a,axis=0).shape

(1, 16)

In [26]:
np.expand_dims(a,axis=1)

array([[ 88],
       [ 77],
       [ 12],
       [ 73],
       [ 89],
       [ 77],
       [ 15],
       [ 58],
       [ 27],
       [ 43],
       [ 38],
       [ 80],
       [ 81],
       [ 37],
       [ 26],
       [200]])

In [32]:
np.expand_dims(a,axis=1).shape

(16, 1)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [34]:
a

array([ 88,  77,  12,  73,  89,  77,  15,  58,  27,  43,  38,  80,  81,
        37,  26, 200])

In [33]:
np.where(a>50)

(array([ 0,  1,  3,  4,  5,  7, 11, 12, 15]),)

In [35]:
#np.where(condition,true,false)
np.where(a>50,0,a)


array([ 0,  0, 12,  0,  0,  0, 15,  0, 27, 43, 38,  0,  0, 37, 26,  0])

In [36]:
np.where(a%2==0,0,a)

array([ 0, 77,  0, 73, 89, 77, 15,  0, 27, 43,  0,  0, 81, 37,  0,  0])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [37]:
#code
a

array([ 88,  77,  12,  73,  89,  77,  15,  58,  27,  43,  38,  80,  81,
        37,  26, 200])

In [39]:
#argmax batata hai ki array mei sabse bda number kis position
np.argmax(a)

np.int64(15)

In [41]:
b

array([[ 2, 97,  2, 84],
       [ 3, 80, 38,  1],
       [54, 94, 56, 74],
       [57, 34, 96, 75],
       [45, 47, 33,  8],
       [38,  7, 93, 71]])

In [44]:

#columnwise bategaa

np.argmax(b,axis=0)

array([3, 0, 3, 0])

In [46]:
#array ka sabse minimum element ka position bateyega

np.argmin(a)

np.int64(2)

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [47]:
a

array([ 88,  77,  12,  73,  89,  77,  15,  58,  27,  43,  38,  80,  81,
        37,  26, 200])

In [48]:
np.cumsum(a)

array([  88,  165,  177,  250,  339,  416,  431,  489,  516,  559,  597,
        677,  758,  795,  821, 1021])

In [49]:
b

array([[ 2, 97,  2, 84],
       [ 3, 80, 38,  1],
       [54, 94, 56, 74],
       [57, 34, 96, 75],
       [45, 47, 33,  8],
       [38,  7, 93, 71]])

In [50]:
np.cumsum(b)

array([   2,   99,  101,  185,  188,  268,  306,  307,  361,  455,  511,
        585,  642,  676,  772,  847,  892,  939,  972,  980, 1018, 1025,
       1118, 1189])

In [51]:
np.cumprod(a)

array([                  88,                 6776,                81312,
                    5935776,            528284064,          40677872928,
               610168093920,       35389749447360,      955523235078720,
          41087499108384960,  1561324966118628480, -4221211226476582912,
        8570028055878264832,  3496388814433421312, -1327611193278803968,
       -7267821623827070976])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [52]:
#code
a

array([ 88,  77,  12,  73,  89,  77,  15,  58,  27,  43,  38,  80,  81,
        37,  26, 200])

In [54]:
np.percentile(a,0)

np.float64(12.0)

In [55]:
np.percentile(a,50)

np.float64(65.5)

In [53]:
np.percentile(a,100)

np.float64(200.0)

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [57]:
a

array([ 88,  77,  12,  73,  89,  77,  15,  58,  27,  43,  38,  80,  81,
        37,  26, 200])

In [56]:
#histogram frequency count batata hai
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([0, 2, 2, 2, 1, 1, 0, 3, 4, 0]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [58]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])



In [60]:
np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [61]:
#isin ek array mei multiple item search karne ke kaam aata hai
items=[10,20,30,40,50,60,70,80,90,100]

In [62]:
np.isin(a,items)

array([False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [63]:
#code
a

array([ 88,  77,  12,  73,  89,  77,  15,  58,  27,  43,  38,  80,  81,
        37,  26, 200])

In [64]:
np.flip(a)

array([200,  26,  37,  81,  80,  38,  43,  27,  58,  15,  77,  89,  73,
        12,  77,  88])

In [65]:
b

array([[ 2, 97,  2, 84],
       [ 3, 80, 38,  1],
       [54, 94, 56, 74],
       [57, 34, 96, 75],
       [45, 47, 33,  8],
       [38,  7, 93, 71]])

In [66]:
np.flip(b)

array([[71, 93,  7, 38],
       [ 8, 33, 47, 45],
       [75, 96, 34, 57],
       [74, 56, 94, 54],
       [ 1, 38, 80,  3],
       [84,  2, 97,  2]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [67]:
#code
a

array([ 88,  77,  12,  73,  89,  77,  15,  58,  27,  43,  38,  80,  81,
        37,  26, 200])

In [68]:
np.put(a,[0,1],[110,530])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [70]:
#code
#110 ko delte karna hai
a

array([110, 530,  12,  73,  89,  77,  15,  58,  27,  43,  38,  80,  81,
        37,  26, 200])

In [72]:
np.delete(a,0)

array([530,  12,  73,  89,  77,  15,  58,  27,  43,  38,  80,  81,  37,
        26, 200])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [76]:
m=np.array([1,2,3,4,5])
n=np.array([3,4,5,6,7])

In [77]:
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [78]:
np.intersect1d(m,n)

array([3, 4, 5])

In [79]:
np.setdiff1d(m,n)

array([1, 2])

In [80]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [81]:
np.in1d(m,n)

/tmp/ipykernel_2929/207282267.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m,n)


array([False, False,  True,  True,  True])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [82]:
a

array([110, 530,  12,  73,  89,  77,  15,  58,  27,  43,  38,  80,  81,
        37,  26, 200])

In [83]:
#code
np.clip(a,a_min=25,a_max=75)

array([75, 75, 25, 73, 75, 75, 25, 58, 27, 43, 38, 75, 75, 37, 26, 75])