#Numpy array and Python lists

In [24]:
#speed
#list
a=[i for i in range(10000000)]
b=[i for i in range(10000000,20000000)]

c=[]
import time
start=time.time()
for i in range (len(a)):
  c.append(a[i]+b[i])
print(time.time()-start)

2.82572078704834


In [25]:
#numpy
import numpy as np
a=np.arange(10000000)
b=np.arange(10000000,20000000)
start=time.time()
c=a + b
print(time.time()-(start))

0.21098995208740234


In [26]:
#memory
a=[i for i in range(10000000)]
import sys
#sys ,means system
sys.getsizeof(a)

89095160

In [27]:
a=np.arange(10000000)
sys.getsizeof(a)

80000112

In [28]:
#uppar wale space ko hum kam kar sakte hai

a=np.arange(10000000,dtype=np.int32)
sys.getsizeof(a)

40000112

#Advanced Indexing

In [29]:
#Fancy indexing
a=np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [30]:
a[[0,2,3,5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [31]:
a[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [32]:
#Boolean indexing

In [33]:
a=np.random.randint(1,100,24).reshape(6,4)

In [34]:
a

array([[96, 47,  8, 27],
       [18, 62, 65, 63],
       [27, 32, 30, 85],
       [67, 10, 89, 46],
       [36, 60, 54, 98],
       [91, 48,  6, 76]])

In [35]:
# find all the grater than 50
a > 50


array([[ True, False, False, False],
       [False,  True,  True,  True],
       [False, False, False,  True],
       [ True, False,  True, False],
       [False,  True,  True,  True],
       [ True, False, False,  True]])

In [36]:
#Numbers grater than 50
a[a>50]

array([96, 62, 65, 63, 85, 67, 89, 60, 54, 98, 91, 76])

In [37]:
#find out even numbers
a % 2 == 0

array([[ True, False,  True, False],
       [ True,  True, False, False],
       [False,  True,  True, False],
       [False,  True, False,  True],
       [ True,  True,  True,  True],
       [False,  True,  True,  True]])

In [38]:
a[a % 2 ==0]

array([96,  8, 18, 62, 32, 30, 10, 46, 36, 60, 54, 98, 48,  6, 76])

In [39]:
#find numbers greater than 50 and are even
#abb  hum do condition apply kar re hai
(a > 50) & (a % 2 == 0)

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [False, False, False,  True]])

In [40]:
a[(a > 50) & (a % 2 == 0) ]

array([96, 62, 60, 54, 98, 76])

In [41]:
#find all numbers not divisible by 7
a[~(a % 7== 0)]

array([96, 47,  8, 27, 18, 62, 65, 27, 32, 30, 85, 67, 10, 89, 46, 36, 60,
       54, 48,  6, 76])

### Broadcasting

The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.

The smaller array is “broadcast” across the larger array so that they have compatible shapes.

In [42]:
a=np.arange(6).reshape(2,3)
b=np.arange(6,12).reshape(2,3)

print(a)
print(b)

print(a+b)


[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 6  8 10]
 [12 14 16]]


In [43]:
a=np.arange(6).reshape(2,3)
b=np.arange(3).reshape(1,3)
print(a)
print(b)
print(a+b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]


#### Broadcasting Rules

**1. Make the two arrays have the same number of dimensions.**<br>
- If the numbers of dimensions of the two arrays are different, add new dimensions with size 1 to the head of the array with the smaller dimension.<br>

**2. Make each dimension of the two arrays the same size.**<br>
- If the sizes of each dimension of the two arrays do not match, dimensions with size 1 are stretched to the size of the other array.
- If there is a dimension whose size is not 1 in either of the two arrays, it cannot be broadcasted, and an error is raised.

<img src = "https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png">

In [45]:
# More examples

a = np.arange(12).reshape(4,3)
b = np.arange(3)

print(a)
print(b)

print(a+b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [46]:
a = np.arange(12).reshape(3,4)
b = np.arange(3)

print(a)
print(b)

print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2]


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [47]:
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)

print(a)
print(b)

print(a+b)

[[0 1 2]]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [48]:
a = np.arange(3).reshape(1,3)
b = np.arange(4).reshape(4,1)

print(a)
print(b)

print(a + b)

[[0 1 2]]
[[0]
 [1]
 [2]
 [3]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [ ]:
a = np.array([1])
# shape -> (1,1)
b = np.arange(4).reshape(2,2)
# shape -> (2,2)

print(a)
print(b)

print(a+b)

[1]
[[0 1]
 [2 3]]
[[1 2]
 [3 4]]


In [ ]:
a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(4,3)

print(a)
print(b)

print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


ValueError: ignored

In [ ]:
a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(4,3)

print(a)
print(b)

print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


ValueError: ignored

### Working with mathematical formulas

In [49]:
a=np.arange(10)
np.sum(a)


np.int64(45)

In [52]:
#sigmoid
def sigmoid(array):
  return 1/(1+np.exp(-array))

a=np.arange(100)

sigmoid(a)



array([0.5       , 0.73105858, 0.88079708, 0.95257413, 0.98201379,
       0.99330715, 0.99752738, 0.99908895, 0.99966465, 0.99987661,
       0.9999546 , 0.9999833 , 0.99999386, 0.99999774, 0.99999917,
       0.99999969, 0.99999989, 0.99999996, 0.99999998, 0.99999999,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.     

In [57]:
#mean square error
actual = np.random.randint(1,50,25)
predicted=np.random.randint(1,50,25)


In [60]:
def mse(actual,predicted):
  return np.mean((actual-predicted)**2)

mse(actual,predicted)

np.float64(425.2)

In [58]:
predicted

array([41, 11, 47, 23, 27, 41, 21, 35, 24, 41,  3, 34,  8,  4, 22, 28, 17,
       13, 25,  5, 45, 42, 12, 45, 19])

In [59]:
actual

array([45, 41, 20, 22,  1, 12, 25, 20,  3, 10, 38, 26,  5, 41, 40, 46, 28,
        3,  7, 30, 33, 18, 35, 36, 22])

In [ ]:
#categorical cross entropy


In [ ]:
# Working with missing values -> np.nan
a = np.array([1,2,3,4,np.nan,6])
a

array([ 1.,  2.,  3.,  4., nan,  6.])

In [63]:
a[~np.isnan(a)]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])