In [1]:
#np.array
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
#1D array
a=np.array([1,2,3])

In [4]:
print(a)

[1 2 3]


In [5]:
print(type(a))

<class 'numpy.ndarray'>


In [6]:
#2-D array
#also called as matyrix because it looked matrix
b=np.array([[1,2,3,4],[5,6,7,8]])

In [7]:
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [8]:
print(type(b))

<class 'numpy.ndarray'>


In [9]:
#3-D array
c=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [10]:
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
#know as tensor
d=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [12]:
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [13]:
#dtyoe
np.array([1,2,3,4],dtype=float)

array([1., 2., 3., 4.])

In [14]:
#dtyoe
#in python non zero value considered as true and 0 considered as false
np.array([1,2,3,4],dtype=bool)

array([ True,  True,  True,  True])

In [15]:
np.array([1,2,3,4],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [16]:
#np.arange
#1=inlcuded and 11=excluded
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
#for alternate number means maine last mei jhoo 2 likha hai wo 2nd number ko strip kar dega
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [18]:
#with reshape
#.rshape(rows,columns)
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [19]:
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [20]:
#np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
np.random.random((3,4))

array([[0.69555111, 0.53607828, 0.1625821 , 0.87151113],
       [0.8092966 , 0.15583928, 0.97857903, 0.90243539],
       [0.25522241, 0.89336459, 0.77250899, 0.30680373]])

In [23]:
#np.linspace
#np.linspace(lownumber,high number,how many number youwant to genrate )
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [24]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Array Attributes

In [25]:

a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)



In [26]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [28]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [29]:
#ndim
#nddim full form is number of dimension
a1.ndim

1

In [30]:
#ndimfunction dimension dekhata hai ki wwo 2D hai ki 3D
a2.ndim

2

In [31]:
a3.ndim

3

In [32]:
#shape
a1.shape

(10,)

In [33]:
a2.shape
#(rows=3,columns=4)

(3, 4)

In [34]:
a3.shape

(2, 2, 2)

In [35]:
#size =array ka size batatahai usme kitne element hai
a3.size

8

In [36]:
a2.size

12

In [37]:
a1.size

10

In [38]:
#itemsize
a3.itemsize

8

In [39]:
#dtype=items ka datatyes batata hai
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


#Changing Datatype

In [40]:

a3.dtype

dtype('int64')

In [41]:
#astype
a3.astype(np.int32)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

#Array Operation

In [42]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

In [43]:
#Scalar operation


#arithematic
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [44]:
#relational
a2 > 16

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [45]:
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [46]:
#vector operations
#arthematic
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [47]:
a1*a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

#Array Function

In [48]:
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1

array([[25., 64., 44.],
       [15., 48., 54.],
       [56.,  1., 17.]])

In [49]:
#max / min / sum / product(prod)
print(np.sum(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))

324.0
1.0
324.0
2605768704000.0


In [50]:
# 0=colums , 1=rows
np.max(a1,axis=1)

array([64., 54., 56.])

In [51]:
#means /median /sts /var
np.mean(a1,axis=1)

array([44.33333333, 39.        , 24.66666667])

In [52]:
np.std(a1,axis=1)

array([15.92342788, 17.1464282 , 23.09882152])

In [53]:
np.median(a1,axis=1)

array([44., 48., 17.])

In [54]:
#trigonometry Functions
np.sin(a1)

array([[-0.13235175,  0.92002604,  0.01770193],
       [ 0.65028784, -0.76825466, -0.55878905],
       [-0.521551  ,  0.84147098, -0.96139749]])

In [55]:
#dot product
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)

In [56]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [57]:
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [58]:
#dot product
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [59]:
#log
np.log(a1)

array([[3.21887582, 4.15888308, 3.78418963],
       [2.7080502 , 3.87120101, 3.98898405],
       [4.02535169, 0.        , 2.83321334]])

In [60]:
#exponent
np.exp(a1)

array([[7.20048993e+10, 6.23514908e+27, 1.28516001e+19],
       [3.26901737e+06, 7.01673591e+20, 2.83075330e+23],
       [2.09165950e+24, 2.71828183e+00, 2.41549528e+07]])

In [61]:
#roung / floor /ceil


In [62]:
#round
np.round(np.random.random((2,3))*100)

array([[79.,  6., 37.],
       [52., 15., 18.]])

In [63]:
#floor

np.floor(np.random.random((2,3))*100)

array([[ 4., 84., 44.],
       [88., 34., 81.]])

In [64]:
#ceil

np.ceil(np.random.random((2,3))*100)

array([[81., 38., 83.],
       [82.,  1., 67.]])

In [65]:
#slicing and indexing

In [66]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [67]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [69]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [70]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
a1[-1]

np.int64(9)

In [72]:
a1[0]

np.int64(0)

In [73]:
a1[-2]

np.int64(8)

In [74]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [75]:
#a2[rows,columns]
a2[1,2]

np.int64(6)

In [76]:
a2[2,3]

np.int64(11)

In [77]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [78]:
#5
a3[1,0,1]

np.int64(5)

In [79]:
#2
a3[0,1,0]

np.int64(2)

In [80]:
#0
a3[0,0,0]

np.int64(0)

In [81]:
#6
a3[1,1,0]

np.int64(6)

#Slicing

In [82]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
#2,3,4
a1[2:5]

array([2, 3, 4])

In [84]:
a1[2:5:2]

array([2, 4])

In [85]:
a1[2:5:1]

array([2, 3, 4])

In [86]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [87]:
a2[0,:]

array([0, 1, 2, 3])

In [88]:
a2[1,:]

array([4, 5, 6, 7])

In [89]:
a2[2,:]

array([ 8,  9, 10, 11])

In [90]:
a2[:,2]

array([ 2,  6, 10])

In [91]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [92]:
a2[1,1:]

array([5, 6, 7])

In [93]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [94]:
 a2[1,0::3]

array([4, 7])

In [95]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [96]:
a2[1:,0::3]

array([[ 4,  7],
       [ 8, 11]])

In [97]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [98]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [99]:
a3=np.arange(27).reshape(3,3,3)


In [100]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [101]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [102]:
a3[1,:,:]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [103]:
a3[0,1,:]

array([3, 4, 5])

In [104]:
a3[1,:,1]

array([10, 13, 16])

In [105]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [106]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [107]:
a3.ndim

3

#Iterating

In [108]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [110]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [111]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [112]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [113]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [114]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


#Reshaping

In [115]:
#Reshaping

In [116]:
#Transpose
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [117]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [118]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [119]:
#ravel=kitne bhi dimension array ko 1-D array mei convert kar deta hai

In [120]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [121]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [122]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [123]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

#Stacking

In [124]:
#horizontal stacking

In [125]:
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)


In [126]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [127]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [128]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [129]:
#vertical stacking

In [130]:
np.vstack((a4,a4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#Splitting

In [131]:
#hsplit

In [132]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [133]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [134]:
#vsplit
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [135]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]